### ISSUE TITLE
Stopped in # Search for boot.img file on the device

### ISSUE THREAD

**Issue by josephmangmang** [sarat1kyan/suDROID#1]
<img width="440" alt="Screenshot 2023-07-17 at 6 17 28 PM" src="https://github.com/54R4T1KY4N/suDROID/assets/7690158/049917e9-ac84-459e-8e76-7a439a4700aa">

I cannot continue, the script can't find the boot.img?
I tried running the command it will return permission denied.

**Comment by sarat1kyan** [comment]
adb root - restarts the adbd daemon with root permissions

this will help, let me know ;)
